### ISSUE TITLE
[BUG] - Reading Complex UDTs returns incorrect data

### ISSUE THREAD

**Issue by tdesroches** [ottowayi/pycomm3#123]
**Pre-checks**
- [ x] running latest version
- [ ] enabled logging 
- [x ] consulted the [docs](https://pycomm3.readthedocs.io/en/latest/) 

**Description**
Reading a complex tag returns wrong values when nested structures are too deep

**Target PLC**
Model:  [e.g. 1756-L82ES]
Firmware Revision: [e.g. 31]
Other Devices in CIP Path:  [e.g. 1756-EN2T v11.002]

**Code Sample**
_Minimal reproduceable code sample_
```python
from  pycomm3 import LogixDriver as ld
from pprint import pprint

if __name__ == "__main__":
    with ld('192.168.0.41') as plc:
        #pprint(plc)
        #pprint(plc.info)


        result = plc.read('gstRecipeDownloaded')
        
        for t in result:
            pprint(t)
```

**Additional context**
The UDT I'm reading is complex in that it has several other UDTs and Array nested, so this may simply be outside of the scope of the library.

This is a sample of what I get:
``` 
 'stCamDataX': [{'arrstMotionData': [{'rEndAngle': 36.0,
                                      'rPosition': 1400.0,
                                      'rStartAngle': 324.0},
                                     {'rEndAngle': 216.0,
                                      'rPosition': 1908.0,
                                      'rStartAngle': 144.0},
                                     {'rEndAngle': 0.0,
                                      'rPosition': 0.0,
                                      'rStartAngle': 0.0},
                                     {'rEndAngle': 0.0,
                                      'rPosition': 0.0,
                                      'rStartAngle': 0.0},
                                     {'rEndAngle': 0.0,
                                      'rPosition': 0.0,
                                      'rStartAngle': 0.0},
                                     {'rEndAngle': 0.0,
                                      'rPosition': 0.0,
                                      'rStartAngle': 0.0},
                                     {'rEndAngle': 0.0,
                                      'rPosition': 0.0,
                                      'rStartAngle': 0.0},
                                     {'rEndAngle': 0.0,
                                      'rPosition': 0.0,
                                      'rStartAngle': 0.0}],
                 'intNumberOfMoves': 2},
 'stCamDataY': [{'arrstMotionData': [{'rEndAngle': 0.0,
                                      'rPosition': 0.0,
                                      'rStartAngle': 0.0},
                                     {'rEndAngle': 2.444985560553941e-41,
                                      'rPosition': 0.0,
                                      'rStartAngle': -2.0},
                                     {'rEndAngle': 2.436577769767992e-41,
                                      'rPosition': -2.4221443955854463e-41,
                                      'rStartAngle': 2.4253673820533934e-41},
                                     {'rEndAngle': 2.459839324275784e-41,
                                      'rPosition': 2.37548115672343e-41,
                                      'rStartAngle': -2.3939782964525175e-41},
                                     {'rEndAngle': 0.0,
                                      'rPosition': 0.0,
                                      'rStartAngle': 0.0},
                                     {'rEndAngle': 0.0,
                                      'rPosition': 0.0,
                                      'rStartAngle': 0.0},
                                     {'rEndAngle': 0.0,
                                      'rPosition': 0.0,
                                      'rStartAngle': 0.0},
                                     {'rEndAngle': 0.0,
                                      'rPosition': 0.0,
                                      'rStartAngle': 0.0}],
                 'intNumberOfMoves': 0},
```
When I take a read by tunneling a little deeper I get what i expect. The first is stCamDataX the second is stCamDataY.  The first one seems to read ok the stCamDataY is not.
```
{'arrstMotionData': [{'rEndAngle': 36.0,
                      'rPosition': 1400.0,
                      'rStartAngle': 324.0},
                     {'rEndAngle': 216.0,
                      'rPosition': 1908.0,
                      'rStartAngle': 144.0},
                     {'rEndAngle': 0.0, 'rPosition': 0.0, 'rStartAngle': 0.0},
                     {'rEndAngle': 0.0, 'rPosition': 0.0, 'rStartAngle': 0.0},
                     {'rEndAngle': 0.0, 'rPosition': 0.0, 'rStartAngle': 0.0},
                     {'rEndAngle': 0.0, 'rPosition': 0.0, 'rStartAngle': 0.0},
                     {'rEndAngle': 0.0, 'rPosition': 0.0, 'rStartAngle': 0.0},
                     {'rEndAngle': 0.0, 'rPosition': 0.0, 'rStartAngle': 0.0}],
 'intNumberOfMoves': 2}


{'arrstMotionData': [{'rEndAngle': 313.0,
                      'rPosition': 675.0,
                      'rStartAngle': 266.0},
                     {'rEndAngle': 94.0,
                      'rPosition': 472.0,
                      'rStartAngle': 46.0},
                     {'rEndAngle': 0.0,
                      'rPosition': 1172.0,
                      'rStartAngle': 0.0},
                     {'rEndAngle': 0.0, 'rPosition': 0.0, 'rStartAngle': 0.0},
                     {'rEndAngle': 0.0, 'rPosition': 0.0, 'rStartAngle': 0.0},
                     {'rEndAngle': 0.0, 'rPosition': 0.0, 'rStartAngle': 0.0},
                     {'rEndAngle': 0.0, 'rPosition': 0.0, 'rStartAngle': 0.0},
                     {'rEndAngle': 0.0, 'rPosition': 0.0, 'rStartAngle': 0.0}],
 'intNumberOfMoves': 2}
```

As you can see it seems to read the first instance of the structure but seems to fall apart afterwards.
I've attached a screen shot of part of the structure.

![image](https://user-images.githubusercontent.com/30838946/114402176-934f7580-9b71-11eb-9c6d-f8d289ccd137.png)

**Comment by ottowayi** [comment]
yeah this is a definitely a bug and I have a feeling I know what it is.  In Logix all the structs are padded to multiples of 4-bytes and I think I didn't account for that in the parsing and my complex UDT test doesn't require any padding.  I see you an have `intNumberOfMoves`, if that is an `INT` and if there aren't any other attributes that use 2 bytes, your UDT is padded with 2 extra bytes. So it parses the first UDT correctly, but leaves the padding in the stream which is then parsed as part of the next UDT.  I'm going to test it out and get back to you with what I find.

**Comment by tdesroches** [comment]
Ok thanks!  intNumberOfMoves is techanically a SINT, not sure if that matters.  If you need anything from me let me know.

**Comment by ottowayi** [comment]
Yep I believe that was it.  I was able to replicate the issue and it was a simple change to fix it.  I pushed it to the develop branch, you can either pull from there or modify `pycomm3/custom_types.py` to add this line:
![image](https://user-images.githubusercontent.com/5274950/114409491-1f609d80-9b70-11eb-9e7c-cdbbbddd3bad.png)

Thanks for finding this, I updated the tests to include this scenario.  I'm currently working on a new release that will hopefully be out really soon.

**Comment by tdesroches** [comment]
I found 2 more similar maybe related issues?  I added the line to my source files as below.  This seems to have fixed the orginal issue.
![image](https://user-images.githubusercontent.com/30838946/114412163-d7934380-9b7a-11eb-940f-33a355a35692.png)

I can make these two seperate issue if you'd prefer.

1) Similar issue reading Same stRecipeDownloaded structure but different part
GOT:
![image](https://user-images.githubusercontent.com/30838946/114412482-2345ed00-9b7b-11eb-9801-d7f5d47bd9dd.png)
Expected:
![image](https://user-images.githubusercontent.com/30838946/114412632-47093300-9b7b-11eb-9f9b-c9ef22eb1402.png)

2) Extra Bytes around string?
There is a string at the top level of the stRecipeDownload.  I can see the name J1305 but its padded front and rear. 
![image](https://user-images.githubusercontent.com/30838946/114412952-92bbdc80-9b7b-11eb-95e6-a92847c786c9.png)


I'm not sure if these are related,  I can make a seperate Issue for each if you'd prefer.

**Comment by ottowayi** [comment]
hmm.. the first one is definitely related and the second may or may not be, so keeping this issue is fine.  If possible, could you send me the UDT so I can try testing against it?  My email is on my profile if you don't want to attach it here.

**Comment by tdesroches** [comment]
Yup no problem, I'll send it now.  On the bright side I don't think you'll encounter a more complex UDT lol

**Comment by ottowayi** [comment]
I think I got it, sometimes there is padding added to the host SINTs for BOOLs inside the UDTs.  I changed the parsing to make sure it starts decoding at the correct offset for each attribute, discarding any padding between them.  It wasn't a hard fix, but difficult to locate.  I pushed the change to the `develop` branch.

**Comment by tdesroches** [comment]
Awesome, tested it and all looks good!

**Comment by ottowayi** [comment]
Great! thanks again for reporting, perfect timing too.  I'm hoping to put out the next release this week, so keep an eye out for it.

**Comment by tdesroches** [comment]
I haven't tried it yet but could this issue also apply for writing it back?



--
Tony Desroches
Programmer - Controls
Linear Transfer Automation

P. 705-735-0000 ext. 251
C. 705-627-9345
F. 705-735-4688
E. ***@***.***> ***@***.******@***.***>

On Mon, 2021-04-12 at 12:34 -0700, ottowayi wrote:

Great! thanks again for reporting, perfect timing too. I'm hoping to put out the next release this week, so keep an eye out for it.

**Comment by ottowayi** [comment]
It absolutely does and I totally forgot to fix that as well. I'll try and fix that tonight too.

**Comment by tdesroches** [comment]
I should be in the office and can test it when its ready.






Tony Desroches
Controls Programmer
Linear Transfer Automation Inc.
C: 705-627-9345
F: 705-735-4688
E: ***@***.***

Confidentiality Notice:
This transmission (including any attachments) may contain confidential information belonging to the sender and is intended only for the use of the party or entity to which it is addressed.  If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, retention or the taking of action in reliance on the contents of this transmission is strictly prohibited.  If you have received this transmission in error, please immediately notify the sender and erase all information and attachments.
________________________________

**Comment by ottowayi** [comment]
I re-opened this issue until I for sure have a fix done.  I just pushed a change that should fix it, but I only did a quick test.  I still need to add unit tests and make sure it's actually fixed.  I might get back to it later tonight, if not I should be able to finish it tomorrow.

**Comment by ottowayi** [comment]
I believe this issue is resolved, please re-open if you discover otherwise.  I've merged all changes to master and will be putting a new release out within the next couple days.
