### ISSUE TITLE
pycomm3 breaks all the existing logging 

### ISSUE THREAD

**Issue by xxBXSD** [ottowayi/pycomm3#148]
**Pre-checks**
- [ ] running latest version - RPi4 running buster, Python3.7.3, pycomm3 V1.1.1
- [ ] enabled logging  - I am using the same logging code for other libraries
- [ ] consulted the [docs](https://pycomm3.readthedocs.io/en/latest/) 

**Description**
When I import pycomm3 using (from pycomm3 import LogixDriver), all my other logging stops functioning
I am trying to remove cpppo from my program and replace it with pycomm3. I was very impressed and excited when I tested pycomm3 as it is written exactly as I expect it to work, and everything worked perfectly. I really hope I can sort out this issue as I don't think I can bear going back to cpppo, after trying pycomm3 :-)

**Code Sample**
This is my function for setting up logging, it works perfectly with all the other libraries that I use. I open a config file, get the log level from the config and set the required logging level.

def cnf_logger():
    # Open the config file
    cfg_dev_tree = OutTree.parse('./' + hostname + '/cfg_data_log.xml')  # parse the config file into a tree
    # Get the log level
    for ll in cfg_dev_tree.iterfind('.//ll'):
        log_level = ll.find('log_level').text
    # Create and configure logger
    if log_level == '0':  # Logs WARNINGS to log file
        logging.basicConfig(filename='./' + hostname + '/Data.log', format='%(asctime)s %(message)s',
                            level=logging.WARNING)
        logging.getLogger('snap7').setLevel(logging.WARNING)
        logging.getLogger('pycomm3').setLevel(logging.WARNING)
    elif log_level == '1':  # Logs local code INFO and snap7 WARNINGS to terminal window
        logging.basicConfig(format='%(asctime)s %(message)s', level=logging.INFO)
        logging.getLogger('snap7').setLevel(logging.INFO)
        logging.getLogger('pycomm3').setLevel(logging.INFO)
    elif log_level == '2':  # Logs local code DEBUG and snap7 WARNINGS to terminal window
        logging.basicConfig(format='%(asctime)s %(message)s', level=logging.DEBUG)
        logging.getLogger('snap7').setLevel(logging.DEBUG)
        logging.getLogger('pycomm3').setLevel(logging.DEBUG)

**Comment by ottowayi** [comment]
Ohh yeah, that was my mistake.  I was adding a `NullHandler` to the root logger and not the pycomm3 one, which leads to `basicConfig` being ignored.  I'll have that fix in the next release, but in the mean time using `basicConfig(..., force=True)` should work.
