### ISSUE TITLE
Generic Message Adding Data to Requests

### ISSUE THREAD

**Issue by molex-steve** [ottowayi/pycomm3#162]
When I use .generic_message it is adding Data to my request:

![image](https://user-images.githubusercontent.com/68919137/125956734-c629e45a-902b-4ebd-8bd6-f468e6ebc73e.png)

Which is resulting in errors:

![image](https://user-images.githubusercontent.com/68919137/125956781-9498fff7-90a1-4bb7-b02b-b8128948059c.png)

**Comment by ottowayi** [comment]
Can you share an example of your code?  That will help me understand where it could be coming from or what the issue is

**Comment by ottowayi** [comment]
no response, closing
