### ISSUE TITLE
[BUG] - get_tag_info throws 'get_tag_info' when tag name is Program:...

### ISSUE THREAD

**Issue by ronytesler** [ottowayi/pycomm3#216]
**Pre-checks**
- [x] running latest version
- [x] enabled logging 
- [x] consulted the [docs](https://pycomm3.readthedocs.io/en/latest/) 

**Description**
_A clear and concise description of what the bug is._
I run this code:
```
plc = LogixDriver(path='192.169.1.2\1')
plc.open()
plc.get_tag_list(program='*')
plc.get_tag_info('Program:P01_Flash._1ms_Flash')

```
data_type: 'BOOL'
tag_type: 'atomic'

The get_tag_info function has this code:
`base, *attrs = tag_name.split(".")`
This changes the full name that appears in the 'self._tags' variable and then it can't be found there in this line:
`data = self._tags[util.strip_array(base)]` (inside `_get_tag_info`).

**Target PLC**
Allen-Bradley, Rockwell Automation
1758-PA72 C

**Comment by ottowayi** [comment]
Thanks for reporting, I just published 1.2.7 with the fix.
