### ISSUE TITLE
Writing Program Files to Rockwell SD Cards

### ISSUE THREAD

**Issue by sjagwork** [ottowayi/pycomm3#249]
Have anyone tried to write a file to an SD Card inside a Rockwell PLC Processor? 
Is there a sample code to start with?

**Comment by ottowayi** [comment]
I have not, so I don't have any example code I could provide.  Do you know if this is possible via a MSG instruction? If so, then it should be possible with this library.  If you can find an example or kb article, I may be able to help you replicate it.
