### ISSUE TITLE
CIP: retrieve all Objects/Classes

### ISSUE THREAD

**Issue by AndrewStuhr** [ottowayi/pycomm3#270]
Do you know if it's possible to retrieve a list of all the objects/classes of a CIP device?  For example the identity object, assembly object, vendor specific objects, etc.

Even though the identity object will always be at 0x01, I think it would be cool to call a function and get a list of every object.

I know some CIP devices only support some commands, so I'm guessing this may not be doable, but thought I'd check.

**Comment by ottowayi** [comment]
Unfortunately, that's not possible.  The only way to know if an object exists is to try and do something with it.  I think the only object guaranteed to exist is the identity one.  You can find a lot of the known objects in the `CIP Reference` page in the documentation, but you'd have to send some sort of request to see if it's supported or not.
