### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by wotori** [ottowayi/pycomm3#271]
**Pre-checks**
- [V] running latest version
- [V] enabled logging 
- [V] consulted the [docs](https://pycomm3.readthedocs.io/en/latest/) 

**Description**
Got the error out of the box running the module with basic example
```
Traceback (most recent call last):
  File "/Users/wotori/git/foam/weintek/pycomm3.py", line 1, in <module>
    from pycomm3 import LogixDriver
  File "/Users/wotori/git/foam/weintek/pycomm3.py", line 1, in <module>
    from pycomm3 import LogixDriver
ImportError: cannot import name 'LogixDriver' from partially initialized module 'pycomm3' (most likely due to a circular import) (/Users/wotori/git/foam/weintek/pycomm3.py)
```

**Code Sample**
_Minimal reproduceable code sample_
```python
from pycomm3 import LogixDriver

with LogixDriver('10.34.40.82') as plc:
    print(plc)
    # OUTPUT:
    # Program Name: PLCA, Device: 1756-L83E/B, Revision: 28.13

    print(plc.info)
```

**Comment by ottowayi** [comment]
This is because your script is named `pycomm3.py`, so Python is trying to import `LogixDriver` from the current script and not the library.  If you rename your script it should work.
