### ISSUE TITLE
Can I communicate with SMC EX-260-SEN module using this library?

### ISSUE THREAD

**Issue by darkhorse0322** [ottowayi/pycomm3#289]
Hi @ottowayi 
Thank you so much for your efforts for this project.

So I am contacting you as I have one question.
So, I am going to communicate with EX-260-SEN module using this library, I know I can use the CIP driver and generic message for this goal.

I have the manual of this device, but I can't know how I can use this library to communicate with this device.
Can you please provide any help for me?
[EXxx-OMP0013-D.pdf](https://github.com/ottowayi/pycomm3/files/12013658/EXxx-OMP0013-D.pdf)

Thanks in advance.

**Comment by ottowayi** [comment]
yeah it should work if you use the `CIPDriver` and `generic_message`, but it depends on what you want to do.  Typically, if you can find some documentation on using the `MSG` instruction, you can replicate that with `generic_message`
