### ISSUE TITLE
Queston: Program Scoped Tags

### ISSUE THREAD

**Issue by coltman151** [ottowayi/pycomm3#40]
Is there a way to handle program-scoped tags? I've tried adding "Program:{myprogram}.{tagtoread}" but I only get an invalid tag request from it.

**Comment by coltman151** [comment]
I figured it out, it's on the docs website. You must set LogixDriver init_program_tags=True before calling plc.read('Program:{desiredprogram}.{tagtoread}.

**Comment by ottowayi** [comment]
I'm reopening this because there may be an issue, you should not need the separate call to get_tag_list, just the init arg.

**Comment by ottowayi** [comment]
I just double checked and it works with only ``init_program_tags=True``.  You will need to use the format of ``'Program:{program_name}.{tag_name}'``, but it shouldn't be any different than using program tags in FTView or other HMIs. I added a few tests for them too.  Feel free to re-open this issue if you're still having to call ``get_tag_list`` separately, but you shouldn't need to.

**Comment by coltman151** [comment]
Okay I'll give it a try again when I'm back in front of a PLC. I'm pretty weak with python, so it very well could have been me.

**Comment by souirite** [comment]
I tried using the method you've stated above and I'm still having issues.
This is how my code is structured:
plc = LogixDriver('136.13.0.11/2', init_program_tags=True)
plc.open()
program_name ='S02_StnL010_TT'
tag_name = 'zzTypeIndex'
print(plc.read(f'Program:{program_name}.{tag_name}'))
plc.close()

The printed is result is this:
Program:S02_StnL010_TT.zzTypeIndex, None, None, Destination unknown, class unsupported, instance undefined or structure element undefined (see extended status) - Extended status out of memory  (05, 00)

**Comment by ottowayi** [comment]
Can you try adding `plc._cfg['use_instance_ids'] = False` before reading the tag.  If that works, I have a bug.  If not, then something else is wrong.  I have a feeling that using instance ids for program tags doesn't work, but I have no hardware that I can test that on.  My only Logix device is v20, v21 was when instance id support was added.

**Comment by slowMelon01** [comment]
I am working with @souirite on this and I've tried adding `plc._cfg['use_instance_ids'] = False` and it worked.
Code:
`plc = LogixDriver('136.13.0.11/2', init_program_tags=True)`
`plc.open()`
`program_name ='S02_StnL010_TT'`
`tag_name = 'zzTypeIndex'`
`plc._cfg['use_instance_ids'] = False`
`print(plc.read(f'Program:{program_name}.{tag_name}'))`
`plc.close()`

Output:
Program:S02_StnL010_TT.zzTypeIndex, 1, DINT, None

If it helps, here is the hardware information we are using:
vendor: Rockwell Automation/Allen-Bradley
product_type: Programmable Logic Controller
product_code: 213
revision: {'major': 31, 'minor': 12}
status: b'`1'
serial: 01105868
product_name: 1756-L83ES/B
keyswitch: REMOTE RUN

**Comment by ottowayi** [comment]
Well fuck. I wish I would have looked at your comment before I published the latest release literally 5 minutes beforehand.  Oh well, I'll try and get a fix out today.

**Comment by ottowayi** [comment]
If you can try making a small code change an verify that it fixes the issue, I can publish a new release. 

In `pycomm3/packets/util.py` line 78 inside the `tag_request_path` function, this condition needs to be added:
![image](https://user-images.githubusercontent.com/5274950/114938976-65825f00-9e05-11eb-997d-a05484e8c63f.png)

If that works for you without setting the `use_instance_ids` setting, I can get a new release out right away.  I already confirmed it doesn't break anything with my PLC.

**Comment by slowMelon01** [comment]
I will look into this tomorrow morning.

**Comment by ottowayi** [comment]
Awesome thanks.

**Comment by slowMelon01** [comment]
I've added the line of code you asked and it still works when I removed the `plc._cfg['use_instance_ids'] = False` code before I read the tag.

Cheers for your help.

**Comment by ottowayi** [comment]
Great, thanks for doing that.  I just published the new release with the fix (1.1.1).
