### ISSUE TITLE
STRING array write stops at 361 (0-360)  -- Writing arrays not truncating values at request element limit

### ISSUE THREAD

**Issue by MikeDausch** [ottowayi/pycomm3#42]
Attempting to write 401 STRINGs stops at 360 element.
I believe this used to work. I get no errors.
Thank you for looking at this.

**Comment by ottowayi** [comment]
Hmm, I just tried it on a v24 L73 with no issues: 

![image](https://user-images.githubusercontent.com/5274950/82359308-57e21080-99cd-11ea-8a6e-dbaaf86fa488.png)

Using this code:

    with LogixDriver('10.61.50.4/10') as plc:
        num = 500
        lines = [f'Test line {i} out of {num}.' for i in range(num)]
        plc.write((f'TestStrings{{{num}}}', lines))

Could you share your code and maybe some information on about the PLC? Also, you can confirm you're running the latest version with the command: ``pip show pycomm3``.  My email is also listed in there, so you can email me if you don't want to post anything publicly.

**Comment by ottowayi** [comment]
The docs state that the value list will be truncated to the limit in the request (the '{x}') if it is too long, this does not appear to be the case. It attempts to write beyond that limit and past the bounds of the array.

**Comment by ottowayi** [comment]
fixed in version 0.6.2
