### ISSUE TITLE
Client/Scanner Application

### ISSUE THREAD

**Issue by sergio-vedois** [ottowayi/pycomm3#56]
Hi,

I need to write an application (client/scanner) that  establish a communication with an ETHERNET/IP adapter/server using both explicit and implicit(I/O) messaging.
The adapter will be coded in C/C++ using EIPStackGroup/OpENer library.

So, my questions are:
Is This library meant for that ?
Which is the max polling rate ?

I Thank in advance for the answers.

Sérgio

**Comment by ottowayi** [comment]
This library is aimed at being a Ethernet/IP client for reading/writing tags in a Control/CompactLogix PLC.  It's intended for quick/convenient access to data inside a PLC and not recommended for mission-critical systems.  Those systems would be better off using a library from a well-known vendor who has the time and resources to make sure their driver is stable and is in full compliance with CIP specs.   I believe OpENer implements just the base CIP services, while this library primarily implements the Rockwell-specific client services from their [Data Access](https://literature.rockwellautomation.com/idc/groups/literature/documents/pm/1756-pm020_-en-p.pdf) manual.  It also only supports explicit messaging.
