### ISSUE TITLE
disable debug logging

### ISSUE THREAD

**Issue by mytalala** [ottowayi/pycomm3#62]
i want to disable debug level logging, but keep errors. i tried:

`
logging.getLogger("pycomm3").setLevel(logging.ERROR)
`

but it doesn't do anything. i use same line to disable _requests_ lib logging and it works fine

**Comment by ottowayi** [comment]
That was something that I broke and didn't notice when I removed the autologging dependency.  I only had the __qualname__ for the logger name, so you would have to set the level on every class logger.  I was missing the module name, so `pycomm3` wasn't the root logger for the library anymore.  This should be fixed now in v0.9.2.

**Comment by mytalala** [comment]
nice! i will wait for v0.9.2
thanks

**Comment by ottowayi** [comment]
No problem, it was a mistake on my part.  I published it so you should be able to update anytime
