### ISSUE TITLE
Support for ESP32

### ISSUE THREAD

**Issue by ivancho523** [ottowayi/pycomm3#77]
Hello
How can I use this library with an ESP32, what changes should I make to be able to use it in a microcontroller? is it possible to use it with micropython?

**Comment by ottowayi** [comment]
I haven't used micropython, but I don't think it will run as-is.  It looks like they only support Python 3.4 (with asyncio keywords from 3.5), this library is Python 3.6 and up.  To get it to run on micropython, you'd have to remove the type hinting and f-strings for sure, but there might be more as well.  Some imports would need to be changed to the `u` version, like `socket`, `struct`, etc.  If you'd like to make a micropython fork you're more than welcome and I can try and answer any questions, but I don't have any plans nor the time needed to support it.
